# Generated by Django 5.0.4 on 2024-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_token',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
