# Generated by Django 4.2.5 on 2023-09-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('group', models.CharField()),
                ('sc_type', models.CharField()),
                ('index_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NSEStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField()),
                ('high', models.CharField()),
                ('low', models.CharField()),
                ('close', models.CharField()),
                ('last', models.CharField()),
                ('prevclose', models.CharField()),
                ('no_trades', models.CharField()),
                ('no_shrs', models.CharField()),
                ('net_turnov', models.CharField()),
                ('td_clo_indi', models.CharField()),
                ('date_show', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='NSEFOStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField()),
                ('high', models.CharField()),
                ('low', models.CharField()),
                ('close', models.CharField()),
                ('last', models.CharField()),
                ('prevclose', models.CharField()),
                ('no_trades', models.CharField()),
                ('no_shrs', models.CharField()),
                ('net_turnov', models.CharField()),
                ('td_clo_indi', models.CharField()),
                ('date_show', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='MCXStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField()),
                ('high', models.CharField()),
                ('low', models.CharField()),
                ('close', models.CharField()),
                ('last', models.CharField()),
                ('prevclose', models.CharField()),
                ('no_trades', models.CharField()),
                ('no_shrs', models.CharField()),
                ('net_turnov', models.CharField()),
                ('td_clo_indi', models.CharField()),
                ('date_show', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='BSEStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField()),
                ('high', models.CharField()),
                ('low', models.CharField()),
                ('close', models.CharField()),
                ('last', models.CharField()),
                ('prevclose', models.CharField()),
                ('no_trades', models.CharField()),
                ('no_shrs', models.CharField()),
                ('net_turnov', models.CharField()),
                ('td_clo_indi', models.CharField()),
                ('date_show', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
            ],
        ),
    ]
