# Generated by Django 4.2.5 on 2023-09-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='index_type',
            new_name='stock_index_type',
        ),
    ]
