# Generated by Django 4.2.5 on 2023-09-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0002_rename_index_type_company_stock_index_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Line')),
                ('content', models.JSONField()),
                ('size', models.IntegerField(null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('title', models.CharField()),
            ],
        ),
    ]
