# Generated by Django 4.2.5 on 2023-09-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0003_chart_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='dashboard_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.dashboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
