# Generated by Django 4.2.5 on 2023-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0004_chart_dashboard_id_chart_name_chart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
