# Generated by Django 5.0.2 on 2024-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0005_chart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='content',
            field=models.JSONField(default=None),
        ),
    ]
