# Generated by Django 5.0.2 on 2024-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0006_alter_chart_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
