# Generated by Django 5.0.2 on 2024-03-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0007_company_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(default=''),
        ),
    ]
