# Generated by Django 5.0.2 on 2024-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0008_company_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
