# Generated by Django 5.0.2 on 2024-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0010_dashboard_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
