# Generated by Django 5.0.2 on 2024-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0012_dashboard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('value', models.CharField()),
                ('db_operator', models.CharField()),
            ],
        ),
    ]
