# Generated by Django 5.0.2 on 2024-03-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0013_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_e', models.CharField()),
                ('face_value', models.CharField()),
                ('market_cap', models.CharField()),
                ('employees', models.CharField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
            ],
        ),
    ]
