# Generated by Django 5.0.2 on 2024-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0014_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='employees',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='face_value',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='market_cap',
            field=models.CharField(null=True),
        ),
    ]
