services:
  # rabbit1:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit1"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "user"
  #     RABBITMQ_DEFAULT_PASS: "password"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "5672:5672"
  #     - "15673:15672"
  #   labels:
  #     NAME: "rabbitmq1"
  web:
    build: .
    # command: python jkinda_stocks/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    # depends_on:
    #   - rabbit1
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
