# Generated by Django 5.0.4 on 2024-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
