# Generated by Django 5.0.2 on 2024-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='data',
            field=models.TextField(),
        ),
    ]
