# Generated by Django 5.0.4 on 2024-04-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdata', '0002_alter_newsdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='tags',
            field=models.CharField(default=''),
        ),
    ]
