# Generated by Django 5.0.2 on 2024-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdata', '0003_newsdata_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='generic_nouns',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='nouns_phrases',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='tags',
            field=models.CharField(default='', null=True),
        ),
    ]
