# Generated by Django 5.0.2 on 2024-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdata', '0004_newsdata_generic_nouns_newsdata_nouns_phrases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='comp_symbols',
            field=models.CharField(default='', null=True),
        ),
    ]
