# Generated by Django 5.0.2 on 2024-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_remove_financial_company_remove_financial_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField()),
                ('company', models.CharField(default=None)),
                ('purpose', models.CharField(default=None)),
                ('details', models.TextField(default=None)),
                ('date', models.DateField()),
            ],
        ),
    ]
