# Generated by Django 5.0.1 on 2024-01-22 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_data', '0005_chart_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('type', models.CharField(choices=[('1', 'Demo'), ('2', 'Main'), ('3', 'Planned'), ('4', 'Past'), ('5', 'Track')], max_length=3)),
                ('invested', models.CharField()),
                ('returns', models.CharField()),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.CharField()),
                ('current', models.CharField()),
                ('shares', models.IntegerField(null=True)),
                ('bought_at', models.FloatField(null=True)),
                ('date_bought', models.DateTimeField()),
                ('date_released', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock_data.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(through='portfolio.PortfolioStock', to='stock_data.company'),
        ),
    ]
