# Generated by Django 5.0.1 on 2024-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliosnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='invested',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='returns',
            field=models.CharField(default='0'),
        ),
    ]
