# Generated by Django 5.0.1 on 2024-01-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_active_alter_portfolio_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
